// Módulo Armazém (um chunk, carregado só quando a rota é visitada)
export { ArmazemLayout } from './ArmazemLayout'
export { InventarioPage } from './InventarioPage'
export { ProdutoFormPage } from './ProdutoFormPage'
export { ProdutoDetalhePage } from './ProdutoDetalhePage'
export { VisaoGeralPage } from './VisaoGeralPage'
export { MovimentosPage } from './MovimentosPage'
export { MovimentoFormPage } from './MovimentoFormPage'
export { ObrasArmazemPage } from './ObrasArmazemPage'
export { FerramentasPage } from './FerramentasPage'
export { FerramentaFormPage } from './FerramentaFormPage'
export { FerramentaDetalhePage } from './FerramentaDetalhePage'
export { EmprestimoPage } from './EmprestimoPage'
export { DevolucaoPage } from './DevolucaoPage'
