export { RHPage }               from './components/RHPage'
export { HorariosPage }         from './components/HorariosPage'
export { AtribuicaoHorarioPage } from './components/AtribuicaoHorarioPage'
export { AssiduidadePage }       from './components/AssiduidadePage'
export { FaltasPage }            from './components/FaltasPage'
